# Dockerfile.gcc
FROM gcc:15

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake ninja-build git curl wget ca-certificates \
    cppcheck \
 && update-ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /project
CMD ["/bin/bash"]
