# Dockerfile.gcc14
FROM ubuntu:24.04

# Install dependencies
RUN apt update && apt install -y \
    software-properties-common \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    curl \
    lsb-release \
    g++-14 \
    gcc-14

# Set GCC 14 as default
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 \
 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100

# Create working directory
WORKDIR /project

# Default command
CMD ["/bin/bash"]
