# Dockerfile.clang
FROM ubuntu:24.04

# Install dependencies
RUN apt update && apt install -y \
    software-properties-common \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    curl \
    lsb-release \
    clang-19 \
    libc++-19-dev \
    libc++abi-19-dev \
    cppcheck

# Set Clang 19 as default
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100 \
 && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100

# Create working directory
WORKDIR /project

# Default command
CMD ["/bin/bash"]
