name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Run test executable
        shell: pwsh
        run: |
          $exe = Resolve-Path ".\build\${{ matrix.config }}\statistics_test.exe"
          & $exe

      - name: Install cppcheck
        shell: pwsh
        run: choco install cppcheck -y

      - name: Run cppcheck on headers and tests
        shell: pwsh
        run: |
          cppcheck.exe ./include/* ./test/*

  docker-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc] 
        config: [debug, release]
    steps:
      - uses: actions/checkout@v4

      - name: Clean build and install directories
        run: rm -rf out

      - name: Build Docker image (${{ matrix.compiler }})
        run: docker build -f Dockerfile.${{ matrix.compiler }} -t cpp-ci-${{ matrix.compiler }} .

      - name: Configure and build (${{ matrix.compiler }} / ${{ matrix.config }})
        run: >
          docker run --rm -v ${{ github.workspace }}:/project -w /project cpp-ci-${{ matrix.compiler }}
          bash -lc "cmake --preset linux-${{ matrix.compiler }}-${{ matrix.config }} &&
                    cmake --build out/build/linux-${{ matrix.compiler }}-${{ matrix.config }}"

      - name: Run tests (${{ matrix.compiler }} / ${{ matrix.config }})
        run: >
          docker run --rm -v ${{ github.workspace }}:/project -w /project cpp-ci-${{ matrix.compiler }}
          ./out/build/linux-${{ matrix.compiler }}-${{ matrix.config }}/statistics_test
