name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Run test executable
        shell: pwsh
        run: |
          $exe = Resolve-Path ".\\build\\${{ matrix.config }}\\test_statistics.exe"
          & $exe

  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang18, gcc14]
        config: [debug, release]

    steps:
      - uses: actions/checkout@v4

      - name: Clean build and install directories
        run: rm -rf out

      - name: Build Docker image
        run: docker build -f Dockerfile.${{ matrix.compiler }} -t cpp-ci-${{ matrix.compiler }} .

      - name: Configure and build with CMake inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project cpp-ci-${{ matrix.compiler }} \
          bash -c "cmake --preset linux-${{ matrix.compiler }}-${{ matrix.config }} && \
                   cmake --build out/build/linux-${{ matrix.compiler }}-${{ matrix.config }}"

      - name: Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project cpp-ci-${{ matrix.compiler }} \
          ./out/build/linux-${{ matrix.compiler }}-${{ matrix.config }}/test_statistics
