name: gcc

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gcc
          load: true
          tags: cpp-ci-gcc:latest
          cache-from: type=gha,scope=dockerfile-gcc
          cache-to: type=gha,mode=max,scope=dockerfile-gcc

      - name: Configure & Build (${{ matrix.config }})
        run: >
          docker run --rm
          -v ${{ github.workspace }}:/project
          -w /project
          cpp-ci-gcc
          bash -lc "cmake --preset linux-gcc-${{ matrix.config }} &&
                    cmake --build out/build/linux-gcc-${{ matrix.config }}"

      - name: Run tests (${{ matrix.config }})
        run: >
          docker run --rm
          -v ${{ github.workspace }}:/project
          -w /project
          cpp-ci-gcc
          ./out/build/linux-gcc-${{ matrix.config }}/statistics_test
